# These are supported funding model platforms

#patreon: # Replace with a single Patreon username

github: enginescript
ko_fi: enginescript
buy_me_a_coffee: enginescript
liberapay: enginescript
thanks_dev: gh/pdowney