# GZip

# Cloudflare will respect your compression level.

# text/html is always compressed by GZip
gzip on;
gzip_buffers 16 8k;
gzip_comp_level 4;
gzip_http_version 1.1;
gzip_min_length 1024;
gzip_proxied any;
gzip_vary on;
gzip_types
  application/atom+xml
  application/geo+json
  application/json
  application/ld+json
  application/manifest+json
  application/rdf+xml
  application/rss+xml
  application/vnd.ms-fontobject
  application/vnd.apple.mpegurl
  application/wasm
  application/xhtml+xml
  application/xml
  application/xslt+xml
  font/otf
  font/sfnt
  font/ttf
  image/bmp
  image/svg+xml
  image/x-icon
  text/calendar
  text/css
  text/csv
  text/javascript
  text/markdown
  text/plain
  text/xml
  text/vcard
  text/vtt;
