# This workflow automatically comments out any uncommented commands under the
# '# Start Normal Automatic Upgrade' and '# Start Emergency Automatic Upgrade'
# sections in the auto-upgrade scripts if they are older than 7 days. It adds a
# date comment above commented lines and labels the commit as 'automated'.
#
# Runs daily and on manual dispatch.

name: Comment Old Auto Upgrade

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3am UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  comment-old-auto-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Comment old auto-upgrade commands
        id: comment_auto_upgrade
        run: |
          python .github/scripts/comment_old_auto_upgrade.py

      - name: Commit and push changes
        if: steps.comment_auto_upgrade.outputs.auto_upgrade_changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scripts/functions/auto-upgrade/normal-auto-upgrade.sh scripts/functions/auto-upgrade/emergency-auto-upgrade.sh
          git diff --cached --quiet || git commit -m "chore: comment out old auto-upgrade commands after 7 days [automated]"
          git push

      - name: Add label to commit (if changes made)
        if: steps.comment_auto_upgrade.outputs.auto_upgrade_changed == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: automated
