name: File Validation

on:
  push:
    paths:
      - '**.sh'
      - '**.conf'
      - '**.txt'
  pull_request:
    paths:
      - '**.sh'
      - '**.conf'
      - '**.txt'

permissions:
  contents: write
  pull-requests: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install dos2unix
      run: sudo apt-get install -y dos2unix
    
    - name: Fix Line Endings
      run: |
        find . -type f -name "*.sh" -exec dos2unix {} \;
    
    - name: Fix File Permissions
      run: |
        find . -type f -name "*.sh" -exec chmod 644 {} \;
    
    - name: Fix Trailing Whitespace
      run: |
        find . -type f -not -path "./.git/*" -exec sed -i 's/[[:blank:]]*$//' {} \;
    
    - name: Fix File Names
      run: |
        find . -type f -name "* *" -not -path "./.git/*" -exec bash -c '
          mv "$0" "${0// /_}"
        ' {} \;
    
    - name: Check for Changes
      id: check_changes
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "changes_found=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request if Changes Made
      if: steps.check_changes.outputs.changes_found == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "style: fix file formatting issues"
        title: "style: automatic file formatting fixes"
        body: |
          Automated fixes for:
          - Line endings (CRLF → LF)
          - File permissions (→ 644)
          - Trailing whitespace removal
          - File names (spaces → underscores)
        branch: fix-file-validation
        delete-branch: true
        labels: |
          automated
          style