# This workflow watches for new releases in the EngineScript-Simple-Site-Exporter repository
# and triggers the sync-plugin-versions-readme workflow when a new release is detected.

name: Watch Simple Site Exporter Releases

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-for-new-releases:
    runs-on: ubuntu-latest
    permissions:
      # Required for repository dispatch events
      contents: read
      # Required for creating repository dispatch events
      actions: write
    steps:
      - name: Check for new releases
        id: check
        run: |
          # Ensure jq is installed
          if ! command -v jq &> /dev/null; then
            echo "jq is required but not installed. Installing now..."
            sudo apt-get update && sudo apt-get install -y jq
          fi
          
          # Get the latest release version from GitHub API
          echo "Fetching latest release from EngineScript-Simple-Site-Exporter repository..."
          response=$(curl -s -o response.json -w "%{http_code}" https://api.github.com/repos/EngineScript/EngineScript-Simple-Site-Exporter/releases/latest)
          
          # Check if the API call was successful
          if [ "$response" -ne 200 ]; then
            echo "Error: Failed to fetch release information. HTTP status code: $response"
            cat response.json
            exit 1
          fi
          
          latest_version=$(jq -r .tag_name response.json)
          if [ "$latest_version" = "null" ] || [ -z "$latest_version" ]; then
            echo "Error: Could not extract version from API response"
            cat response.json
            exit 1
          fi
          
          echo "Latest version: $latest_version"
          
          # Create a repository dispatch event to trigger the readme update
          echo "Triggering sync-plugin-versions-readme workflow..."
          dispatch_response=$(curl -s -o dispatch_response.json -w "%{http_code}" -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"simple-site-exporter-release", "client_payload":{"version":"'"$latest_version"'"}}')
          
          # Check if the dispatch event was successful
          if [ "$dispatch_response" -ne 204 ]; then
            echo "Error: Failed to create repository dispatch event. HTTP status code: $dispatch_response"
            cat dispatch_response.json
            exit 1
          fi
          
          echo "Successfully triggered sync-plugin-versions-readme workflow"
